### PR TITLE
Add Step Function Flag, rename eegThresh for clarity

### PR DESCRIPTION
**Pull request by henrymj**
Renamed var `eegThresh` to `eegAbsThresh` for clarity, and changed the value to 100 to match ERPLab's example.

Added a call ERPLab's step function rejection using Gisella's params - 60 microvolt jump between halves in a 250ms window, which shifts by 20ms.

Made some value changes for arbitrary variables `timelockCodes`, `subjectParentDir`, `startEvent` and `endEvent`

### CODE REVIEW

**Comment by WilliamThyer** [comment]
I really like all the changes you listed in the description! It will be great to have the step function check, and the variable name changes look good.

However, it looks like you also changed some parameters specific to the acacia study in the first commit, but didn't change all of them back in the second commit. Stuff like `subjectParentDir`, timelockCodes`, etc. Could you modify lines 9, 10, 21, 22, 23, and 27 to match the original script (I think that's all of them). That way they'll still work with the test data!

**Review by WilliamThyer — CHANGES_REQUESTED** [review]
I really like all the changes you listed in the description! It will be great to have the step function check, and the variable name changes look good.

However, it looks like you also changed some parameters specific to the acacia study in the first commit, but didn't change all of them back in the second commit. Stuff like subjectParentDir, timelockCodes, etc. Could you modify lines 9, 10, 21, 22, 23, and 27 to match the original script (I think that's all of them). That way they'll still work with the test data!

**Comment by colinquirk** [comment]
I'm so proud

**Comment by WilliamThyer** [comment]
Your legacy lives on Colin!

**Comment by henrymj** [comment]
Updated!

**Review by WilliamThyer — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
